spring:
  application:
    name: student-service
  h2:
    console.enabled: true
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url:jdbc:h2:mem:mydb
  username: sa
  password: password
  driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
