spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/student/**,/api/v1/students/**
        - id: transaction-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/transaction/**,/api/v1/transactions/**,/api/v1/receipt/**

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
